apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uxm82mj5x-go 
  janus-idp.io/tekton: uxm82mj5x-go
  backstage.io/kubernetes-id: uxm82mj5x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uxm82mj5x-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml