apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uxm82mj5x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uxm82mj5x-go 
  name: uxm82mj5x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uxm82mj5x-go 
